
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC&useUnicode=true
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      max-active: 20
      max-idle: 20
      max-wait: 6000
    username: root
server:
  port: 9090
  servlet:
    context-path: /shop-manger
mybatis:
  type-aliases-package: com.example.entity
logging:
  level:
    com.example.mapper: debug
debug: true
elasticsearch:
  address: 192.168.236.131