server:
  port: 8081
jwt:
  tokenHeader: Authoriztion
  secret: yeb-secret
  expiration: 604800
  tokenHead: Bearar
#swagger: "2.0"
#info:
#  title: Sample API
#  description: API description in Markdown.
#  version: 1.0.0
#components:
#  securitySchemes:
#    bearerAuth:
#      type: http
#      scheme: bearer
#      bearerFormat: JWT
#security:
#  - bearerAuth: []
debug: true
