spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/soup?serverTimezone=GMT%2B8characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

