server:
  port: 8080
mybatis-plus:
  type-aliases-package: com.example.pixiv.model
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/pix?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
logging:
  config: classpath:logback-spring.xml
  level:
    com.example.pixiv.entity.mapper: trace
