spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vite?setUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

  